### ISSUE TITLE
Inquiry about pre-trained checkpoint

### ISSUE THREAD

**Issue by harryma123** [eventbasedvision/eTraM#6]
Hi, thanks for the great work. May I ask if we can have access to the pre-trained checkpoint of RVT-base on eTram? By the way, it seems that the RVT model only supports the h5 format, but I can only find raw dvs format from the download link. Do you have any plans to upload the h5 format dataset in the future? I'm looking forward to your reply.

**Comment by aayush-v** [comment]
Hi @harryma123 thank you for reaching out and for your interest in eTraM. Regarding your question, we've made the RVT-base checkpoint available along with the data in .h5 format. You can now access both resources conveniently. If you encounter any further issues or have additional questions, please don't hesitate to ask.

**Comment by harryma123** [comment]
Hi @aayush-v , thanks for your prompt response. I tested the ckpt and found that it only supports ('pedestrian', 'car', 'bicycle'). However, in your paper, the eTram dataset contains 8 different classes. So, I would like to know if you have an 8-class ckpt available.

By the way, if I want to generate my own customized dataset, does the class ID matter for training? If I hard code it to zero, would it still make sense?

**Comment by aayush-v** [comment]
Hi @harryma123, our baselines are established on the three major traffic participant categories - Pedestrians, Vehicles (car, bus, truck, tram), and Micro-mobility (bicycle, bike, wheelchair) and the checkpoint corresponding to that experiment has been made available. In addition to these annotations, we also provide the annotations of 8 different classes as mentioned in the paper.

As for your second question, the class ID does matter since training is done for an object detection task. If you hard code all class IDs to zero your model will essentially learn to localize the presence of an object, and not actually classify them.

**Comment by harryma123** [comment]
Hi @aayush-v , I'm sorry if I haven't described it clearly. I actually meant the track ID, not the class ID. Does it make a difference for model training? Additionally, I would like to know if you have a pretrained checkpoint for YOLOv8 available.

**Comment by aayush-v** [comment]
The tracking IDs do not matter for the object detection algorithms used. They completely depend on Class IDs, so it would not make a difference if you hard coded them to zero.
As of now, we do not have any immediate plans for a YOLOv8 pretrained checkpoint, nevertheless you can utilize the code in our repository to train the model.
